name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container: debian:bookworm
    permissions:
      contents: write      # required to create a release and upload assets

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            cmake build-essential git libgtest-dev

      - name: Build and install GTest
        run: |
          cmake -S /usr/src/googletest -B /usr/src/googletest/build -DCMAKE_BUILD_TYPE=Release
          cmake --build /usr/src/googletest/build
          cmake --install /usr/src/googletest/build

      - name: Build
        run: |
          cmake --preset release
          cmake --build --preset release

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/release/bin/command-line-tools/image-encryptor
